### ISSUE TITLE
Empty alternativeNames

### ISSUE THREAD

**Issue by coret** [netwerk-digitaal-erfgoed/geonames-harvest#2]
Some Geonames don't have an "alternatenames" value, the current RML mapping produces an empty value. Is this desired?

```
<https://sws.geonames.org/2743475> <https://sws.geonames.org/ontology#name> "Zwolle-IJsselkanaal".
<https://sws.geonames.org/2743475> <https://sws.geonames.org/ontology#alternateName> "".
```

**Comment by EnnoMeijers** [comment]
I know, this problem has been keeping me busy for sometime but I could not fix it in RML :( 
I tried to use an ['if' function](https://rml.io/docs/rmlmapper/default-functions/#if) to detect these cases but I got stuck. In the query I am using for the NoT I filtered out the empty alternateNames see [geonames.rq](https://github.com/netwerk-digitaal-erfgoed/network-of-terms/blob/geonames/packages/network-of-terms-catalog/catalog/queries/search/geonames.rq). 
Maybe @mielvds can help us out?

**Comment by mielvds** [comment]
I think the underlying problem is the (not) identification of null values in CSV: there is no distinction between "" and an empty value. 
I'm wondering to what extent the RML processor supports the CSVW vocabulary, because you could use 
```
rdf:type csvw:Table;
csvw:url "geonamesplus.txt";
csvw:null ""
```
In this case, "" would be recognized as any empty value and it would not produce a triple. Of course, this would be for all occurences of "", also the ones that are intentionally empty strings.

(This should work actually, see https://github.com/RMLio/rmlmapper-java/blob/master/src/test/resources/test-cases-CSVW/RMLTC1002a_null-CSVW/mapping.ttl)

**Comment by EnnoMeijers** [comment]
I did try to use the cvsw:null property but it seems to have no effect. Fixed the problem for now by cleaning up the geonames.nt afterwards using `sed` (see map.sh script).
