### ISSUE TITLE
ADM1 entities have themselves as parentADM1

### ISSUE THREAD

**Issue by ddeboer** [netwerk-digitaal-erfgoed/geonames-harvest#8]
For example:

```rdf
<https://sws.geonames.org/2744011/> <https://www.geonames.org/ontology#featureCode> <https://www.geonames.org/ontology#A.ADM1>.
<https://sws.geonames.org/2744011/> <https://www.geonames.org/ontology#parentADM1> <https://sws.geonames.org/2744011/>.
<https://sws.geonames.org/2744011/> <https://www.geonames.org/ontology#name> "Provincie Zeeland".
```

GeoNames itself does not have a parent ADM1 for this item: https://sws.geonames.org/2744011/about.rdf. 

Is this caused by the source data or the RML mappings?

**Comment by EnnoMeijers** [comment]
This is indeed caused by the RML converter which always adds the ADM1 level. This should be modified to prevent adding the current level (either ADM1 or ADM2). I currently lack the knowledge how to do this in RML. A more easy fix is to adjust the search and lookup queries to filter out these circular links. See the proposed change in https://github.com/netwerk-digitaal-erfgoed/network-of-terms/compare/master...feat-geo
